# https://github.com/kubernetes/helm/blob/master/docs/charts_tips_and_tricks.md
# https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
{{- define "imagePullSecret" }}
{{- printf "{\"auths\": {\"%s\": {\"auth\": \"%s\"}}}" .Values.image.pullSecret.registry (printf "%s:%s" .Values.image.pullSecret.username .Values.image.pullSecret.password | b64enc) | b64enc }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.fullname" . }}-dockercfg
  labels:
{{ include "common.labels.standard" . | indent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
