apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" . }}
  labels:
{{ include "common.labels.standard" . | indent 4 }}
data:
{{/* TODO merge objects */}}
{{ toYaml .Values.configMap.env | indent 2 }}
{{ toYaml .Values.configMap.files | indent 2 }}
