{{- if .Values.configMap.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" . }}
  labels:
{{ include "common.labels.standard" . | indent 4 }}
data:
{{- with .Values.configMap.env }}
{{ toYaml . | indent 2 }}
{{- end }}

{{- with .Values.configMap.files }}
{{ toYaml . | indent 2 }}
{{- end }}
{{- end -}}
