{{- if .Values.configMap.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" . }}
  labels:
{{ include "common.labels.standard" . | indent 4 }}
data:
{{ toYaml (merge (merge (dict) .Values.configMap.env) .Values.configMap.files) | indent 2 }}
{{- end -}}
