apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" . }}
  labels:
{{ include "common.labels.standard" . | indent 4 }}
data:
{{ toYaml (merge .Values.configMap.env .Values.configMap.files) | indent 2 }}
