{{- if .Values.deployment.enabled -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ include "common.fullname" . }}
{{- with .Values.deployment.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
{{ include "common.labels.standard" . | indent 4 }}
{{- with .Values.deployment.labels }}
{{ toYaml .| indent 4 }}
{{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "common.name" . }}
      release: {{ .Release.Name }}
{{- with .Values.deployment.strategy }}
  strategy:
{{ toYaml . | indent 4 }}
{{- end }}
  revisionHistoryLimit: {{ .Values.deployment.revisionHistoryLimit }}
  template:
    metadata:
      name: {{ include "common.fullname" . }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
{{- if .Values.deployment.pod}}
{{- with .Values.deployment.pod.annotations }}
{{ toYaml . | indent 8 }}
{{- end }}
{{- end }}
      labels:
        app: {{ include "common.name" . }}
        release: {{ .Release.Name | quote }}
{{- if .Values.deployment.pod}}
{{- with .Values.deployment.pod.labels }}
{{ toYaml .| indent 8 }}
{{- end }}
{{- end }}
    spec:
      containers:
{{- $root := . }}
{{- with .Values.deployment.pod.containers }}
{{ include "monochart.containers" ( list . $root ) | indent 6 }}
{{- end }}
      volumes:
      - name: storage
      {{- if .Values.persistence }}
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaim | default (include "common.fullname" .) }}
      {{- else }}
        emptyDir: {}
      {{- end }}
      {{- end }}
{{ include "monochart.files.volumes" . | indent 6 }}
{{- end -}}
