{{- if .Values.secret.enabled -}}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "monochart.env.fullname" . }}
  labels:
{{ include "common.labels.standard" . | indent 4 }}
type: Opaque
data:
{{- range $name, $value := .Values.secret.env }}
{{- if not (empty $value) }}
  {{ $name }}: {{ $value | b64enc }}
{{- end }}
{{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "monochart.files.fullname" . }}
  labels:
{{ include "common.labels.standard" . | indent 4 }}
type: Opaque
data:
{{- range $name, $value := .Values.secret.files }}
{{- if not (empty $value) }}
  {{ $name }}: {{ $value | b64enc }}
{{- end }}
{{- end }}

{{- end -}}
