global:
  ## Hyperkube image to use when getting ThirdPartyResources & cleaning up
  ##
  hyperkube:
    repository: quay.io/coreos/hyperkube
    tag: v1.9.6_coreos.0
    pullPolicy: IfNotPresent

## Prometheus-operator image
##
image:
  repository: quay.io/coreos/prometheus-operator
  tag: v0.17.0
  pullPolicy: IfNotPresent

app:
  images:
    alertManager: quay.io/prometheus/alertmanager:v0.14.0
    configReloaded: quay.io/coreos/configmap-reload:v0.0.1
  crd: monitoring.coreos.com

## Node labels for prometheus-operator pod assignment
##
nodeSelector: {}

## If true, collect & send anonymous usage statistics
## Ref: https://github.com/coreos/prometheus-operator#installation
##
sendAnalytics: true

## Prometheus-operator resource limits & requests
## Ref: https://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  limits:
    cpu: 200m
    memory: 300Mi
  requests:
    cpu: 100m
    memory: 50Mi
